title: My Test Blog
author: UniversalBuilder
email: yannick.krempp@unil.ch
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Thhis is just a test bolg, nothing to see here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  universalbuilder # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
